name: CodeQL
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    container:
      # Runner docker image
      image:  ubuntu:20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # You can include multiple languages in the matrix.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
       
    - name: Install dependency
      run: |
         apt update
         apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev bc -y
      shell: bash

    - name: Build the code
      run: |
         echo `nproc`
         make clean all -j `nproc`
      shell: bash
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
