name: CodeQL
on:
  workflow_dispatch:
  
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev bc -y
      shell: bash
      
    - name: Build the code
      run: |
         echo `nproc` "cores detected on runner."
         make clean vmlinux -j `nproc`
      shell: bash

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
