name: CodeQL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # You can include multiple languages in the matrix.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    - name: Build the code
      run: |
         sudo apt update
         sudo apt upgrade -y
         sudo apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev bc -y
         make clean all
      shell: bash

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
