name: Semgrep
on:
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: self-hosted
    container:
      image: returntocorp/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
